vi:
	vim \
		Makefile \
		./hidui \
		./HIDUI/Core.pm \
		./HIDUI/Config.pm \
		./HIDUI/UI/MainWindow.pm \
		./HIDUI/UI/Manager.pm \
		./HIDUI/UI/NavigableGrid.pm \
		./HIDUI/UI/PresetConfig.pm \
		./HIDUI/ActionRegistry.pm \
		./HIDUI/Actions/EventMapper.pm \
		./HIDUI/Actions/Keyboard.pm \
		./HIDUI/Actions/Mouse.pm \
		./HIDUI/Actions/Presets.pm \
		./HIDUI/Actions/UI.pm \
		./config/defaults.json \
		./README.md \

# Leave blank line above
