vi:
	vim \
		Makefile \
		hidui \
		lib/HIDUI/Core.pm \
		lib/HIDUI/Config.pm \
		lib/HIDUI/EventMapper.pm \
		lib/HIDUI/UI/MainWindow.pm \
		lib/HIDUI/UI/Manager.pm \
		lib/HIDUI/UI/NavigableGrid.pm \
		lib/HIDUI/UI/PresetConfig.pm \
		lib/HIDUI/ActionRegistry.pm \
		lib/HIDUI/Actions/Keyboard.pm \
		lib/HIDUI/Actions/Mouse.pm \
		lib/HIDUI/Actions/Presets.pm \
		lib/HIDUI/Actions/UI.pm \
		config/defaults.json \
		README.md \

# Leave blank line above
# vim: et ts=4 sts=4 sw=4
